### ISSUE TITLE
Crash in the Counselling and Treatment menu while filling in the Contact 2

### ISSUE THREAD

**Issue by ellyasafaa** [opensrp/opensrp-client-anc#663]
### How do we replicate the bug?

Steps to check:

1. Log in to the app
2. Start the contact 2 by clicking one of the clients that has done the first contact, you will then be navigated to the Quick Check page
3. Choose the option of Scheduled contact and fill in the danger signs with none
4. Click 'Proceed to Normal Contact button' in the bottom of the page
5. You can fill in all information on the other menu first, or just click the Counselling and Treatment menu
6. Fill in all information until you reach the page of Deworming and Malaria Prophylaxis
7. Click Next
8. The crash will happen

Testing Device: Samsung A21s Android 10 and 11

### How is this feature expected to work?

It is supposed to navigate you to the next page.

Please kindly also check it @Naima-Bashir and set it to high priority issue. I succeeded to replicate the issue with the exact same step.

### Please Share other relevant information about the bug

The video for the issue can be seen here: https://drive.google.com/file/d/1Q61W0dbgGXgpAoVkP1pjCrr1kThJJihF/view?usp=sharing

**Comment by junaidwarsivd** [comment]
2021-10-11 17:37:23.376 9702-9702/org.smartregister.anc E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.anc, PID: 9702
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.smartregister.anc/org.smartregister.anc.library.activity.MainContactActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
        at org.smartregister.repository.FormDataRepository.<init>(FormDataRepository.java:72)
        at org.smartregister.Context.formDataRepository(Context.java:722)
        at org.smartregister.Context.ziggyService(Context.java:514)
        at org.smartregister.view.activity.SecuredActivity.onCreate(SecuredActivity.java:67)
        at org.smartregister.anc.library.activity.BaseContactActivity.onCreate(BaseContactActivity.java:53)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656

**Comment by junaidwarsivd** [comment]
Updating native-forms dependency to 2.1.11 crash is not occurring.

**Comment by Naima-Bashir** [comment]
SID team to confirm if it has been fixed @ellyasafaa @elwinameylentia
