### ISSUE TITLE
Tree based questions crushes the app when the data becomes huge

### ISSUE THREAD

**Issue by dodosi** [opensrp/opensrp-client-anc#739]
### Affected App or Server Version

v1.6.10

### What kind of support do you need?

We wanted to load tree based question, starting from province-district-sector-cell to village,
As villages are too many, when we put them in the json file, we get the error that "FAILED BINDER TRANSACTION"
And we want to make it loading from province to village.
When we add villages, the json file get more than 55300 lines (SIZE: 1MB)
How can we fix this issue

### What is the acceptance criteria for your support request?

Load tree based question without crushing the app regardless to the size of information in the file.

### Relevant Information

org.smartregister.anc E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1340932)
org.smartregister.anc E/RegisterPresenter:  --> onUniqueIdFetched
    java.lang.RuntimeException: Failure from system
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1720)
        at android.app.Activity.startActivityForResult(Activity.java:5258)
        at androidx.activity.ComponentActivity.startActi
xsi-mbnv-sre

**Comment by ndegwamartin** [comment]
@dodosi could you please add the steps to reproduce this? Along with all resources that will be needed for testing e.g. the villages json file. This can be shared on Slack cc @Naima-Bashir @dubdabasoduba

**Comment by Naima-Bashir** [comment]
@dodosi @neric1 The Ona team needs steps + resources to reproduce for efficient bug fixes/patches. Kindly do so

**Comment by Naima-Bashir** [comment]
response from partner: Replace register.json file contents  by what is provided in the attachment, and run application. The app will crush.
The address_field.json is the json file that contains location hierarchy  (It is already included in register.json)
Reducing the contents solves the issue But we want to access information up to village level.

**Comment by Naima-Bashir** [comment]
Hamza has started the implementation.

**Comment by Naima-Bashir** [comment]
Hi @hamza-vd any updates on this ticket?

**Comment by Naima-Bashir** [comment]
PR has been created by @hamza-vd . Review pending.
