### ISSUE TITLE
[Ona Support Request]: Locations are not loaded in register form

### ISSUE THREAD

**Issue by dodosi** [opensrp/opensrp-client-anc#885]
### Affected App or Server Version

v1.6.14

### What kind of support do you need?

We need to load locations on the form after switching to server using docker, this functionality failed to work.
![image](https://user-images.githubusercontent.com/8068177/190184514-c217f8d1-fca5-4cb4-aee2-df71c72cbfac.png)

### What is the acceptance criteria for your support request?
To add the described functionalities in the app working with the docker server.

### Relevant Information

The apk can be found here.
https://github.com/dodosi/opensrp_rw/releases

**Comment by Naima-Bashir** [comment]
Hi @dodosi Please attached any errors on the logcat on the issue. Also, attach the APK in question.

**Comment by dodosi** [comment]
**On opening the register form, I get these log messages
It does not show provinces spinner, but other locations in other spinners open.**

2022-09-15 09:54:09.382 29868-29868/org.smartregister.anc W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@71919f1
2022-09-15 09:54:09.427 29868-29868/org.smartregister.anc I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
2022-09-15 09:54:09.506 29868-29868/org.smartregister.anc D/ViewRootImpl[Loading]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
2022-09-15 09:54:09.528 29868-29868/org.smartregister.anc D/ViewRootImpl[AncRegistrationActivity]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
2022-09-15 09:54:09.556 29868-29868/org.smartregister.anc D/Surface: Surface::allocateBuffers(this=0x754e330000)
2022-09-15 09:54:09.562 29868-29948/org.smartregister.anc D/OpenSSLLib: OpensslErr:Module:30(110:); file:external/boringssl/src/crypto/fipsmodule/cipher/cipher.c ;Line:563;Function:EVP_CIPHER_CTX_set_key_length
2022-09-15 09:54:09.566 29868-29948/org.smartregister.anc D/Surface: Surface::connect(this=0x754e330000,api=1)
2022-09-15 09:54:09.582 29868-29868/org.smartregister.anc D/Surface: Surface::allocateBuffers(this=0x754dfa4000)
2022-09-15 09:54:09.587 29868-29948/org.smartregister.anc D/OpenSSLLib: OpensslErr:Module:30(110:); file:external/boringssl/src/crypto/fipsmodule/cipher/cipher.c ;Line:563;Function:EVP_CIPHER_CTX_set_key_length
2022-09-15 09:54:09.591 29868-29948/org.smartregister.anc D/Surface: Surface::connect(this=0x754dfa4000,api=1)
2022-09-15 09:54:09.742 29868-29868/org.smartregister.anc W/System.err: org.json.JSONException: Value a26ca9c8-1441-495a-83b6-bb5df7698996 of type java.lang.String cannot be converted to JSONObject
2022-09-15 09:54:09.742 29868-29868/org.smartregister.anc W/System.err:     at org.json.JSON.typeMismatch(JSON.java:112)
2022-09-15 09:54:09.742 29868-29868/org.smartregister.anc W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:163)
2022-09-15 09:54:09.742 29868-29868/org.smartregister.anc W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:176)
2022-09-15 09:54:09.743 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.util.Utils.getLocationsByParentId(Utils.java:1090)
2022-09-15 09:54:09.743 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.widget.ANCSpinnerFactory.populateLocationSpinner(ANCSpinnerFactory.java:147)
2022-09-15 09:54:09.743 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.widget.ANCSpinnerFactory.populateProvince(ANCSpinnerFactory.java:126)
2022-09-15 09:54:09.743 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.widget.ANCSpinnerFactory.getViewsFromJson(ANCSpinnerFactory.java:107)
2022-09-15 09:54:09.743 29868-29868/org.smartregister.anc W/System.err:     at com.vijay.jsonwizard.interactors.JsonFormInteractor$1.run(JsonFormInteractor.java:232)
2022-09-15 09:54:09.743 29868-29868/org.smartregister.anc W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2022-09-15 09:54:09.743 29868-29868/org.smartregister.anc W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-09-15 09:54:09.743 29868-29868/org.smartregister.anc W/System.err:     at android.os.Looper.loop(Looper.java:193)
2022-09-15 09:54:09.743 29868-29868/org.smartregister.anc W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6819)
2022-09-15 09:54:09.743 29868-29868/org.smartregister.anc W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-09-15 09:54:09.743 29868-29868/org.smartregister.anc W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
2022-09-15 09:54:09.743 29868-29868/org.smartregister.anc W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)
2022-09-15 09:54:09.764 29868-29868/org.smartregister.anc W/System.err: org.json.JSONException: Value 8dea599b-d941-4087-8571-d60884f71301 of type java.lang.String cannot be converted to JSONObject
2022-09-15 09:54:09.764 29868-29868/org.smartregister.anc W/System.err:     at org.json.JSON.typeMismatch(JSON.java:112)
2022-09-15 09:54:09.764 29868-29868/org.smartregister.anc W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:163)
2022-09-15 09:54:09.764 29868-29868/org.smartregister.anc W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:176)
2022-09-15 09:54:09.764 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.util.Utils.getLocationsByParentId(Utils.java:1090)
2022-09-15 09:54:09.764 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.widget.ANCSpinnerFactory.populateLocationSpinner(ANCSpinnerFactory.java:147)
2022-09-15 09:54:09.764 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.widget.ANCSpinnerFactory.populateDescendants(ANCSpinnerFactory.java:139)
2022-09-15 09:54:09.765 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.widget.ANCSpinnerFactory.getViewsFromJson(ANCSpinnerFactory.java:109)
2022-09-15 09:54:09.765 29868-29868/org.smartregister.anc W/System.err:     at com.vijay.jsonwizard.interactors.JsonFormInteractor$1.run(JsonFormInteractor.java:232)
2022-09-15 09:54:09.765 29868-29868/org.smartregister.anc W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2022-09-15 09:54:09.765 29868-29868/org.smartregister.anc W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-09-15 09:54:09.765 29868-29868/org.smartregister.anc W/System.err:     at android.os.Looper.loop(Looper.java:193)
2022-09-15 09:54:09.765 29868-29868/org.smartregister.anc W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6819)
2022-09-15 09:54:09.765 29868-29868/org.smartregister.anc W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-09-15 09:54:09.765 29868-29868/org.smartregister.anc W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
2022-09-15 09:54:09.765 29868-29868/org.smartregister.anc W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)
2022-09-15 09:54:09.790 29868-29868/org.smartregister.anc W/System.err: org.json.JSONException: Value 2c76e252-c92b-401a-8232-779b5d09fddf of type java.lang.String cannot be converted to JSONObject
2022-09-15 09:54:09.790 29868-29868/org.smartregister.anc W/System.err:     at org.json.JSON.typeMismatch(JSON.java:112)
2022-09-15 09:54:09.790 29868-29868/org.smartregister.anc W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:163)
2022-09-15 09:54:09.790 29868-29868/org.smartregister.anc W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:176)
2022-09-15 09:54:09.790 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.util.Utils.getLocationsByParentId(Utils.java:1090)
2022-09-15 09:54:09.790 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.widget.ANCSpinnerFactory.populateLocationSpinner(ANCSpinnerFactory.java:147)
2022-09-15 09:54:09.790 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.widget.ANCSpinnerFactory.populateDescendants(ANCSpinnerFactory.java:139)
2022-09-15 09:54:09.790 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.widget.ANCSpinnerFactory.getViewsFromJson(ANCSpinnerFactory.java:109)
2022-09-15 09:54:09.790 29868-29868/org.smartregister.anc W/System.err:     at com.vijay.jsonwizard.interactors.JsonFormInteractor$1.run(JsonFormInteractor.java:232)
2022-09-15 09:54:09.790 29868-29868/org.smartregister.anc W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2022-09-15 09:54:09.790 29868-29868/org.smartregister.anc W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-09-15 09:54:09.790 29868-29868/org.smartregister.anc W/System.err:     at android.os.Looper.loop(Looper.java:193)
2022-09-15 09:54:09.790 29868-29868/org.smartregister.anc W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6819)
2022-09-15 09:54:09.790 29868-29868/org.smartregister.anc W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-09-15 09:54:09.790 29868-29868/org.smartregister.anc W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
2022-09-15 09:54:09.790 29868-29868/org.smartregister.anc W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)
2022-09-15 09:54:09.815 29868-29868/org.smartregister.anc W/System.err: org.json.JSONException: Value f90a81e0-afee-475d-a986-7684aa3132f1 of type java.lang.String cannot be converted to JSONObject
2022-09-15 09:54:09.815 29868-29868/org.smartregister.anc W/System.err:     at org.json.JSON.typeMismatch(JSON.java:112)
2022-09-15 09:54:09.815 29868-29868/org.smartregister.anc W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:163)
2022-09-15 09:54:09.815 29868-29868/org.smartregister.anc W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:176)
2022-09-15 09:54:09.815 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.util.Utils.getLocationsByParentId(Utils.java:1090)
2022-09-15 09:54:09.815 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.widget.ANCSpinnerFactory.populateLocationSpinner(ANCSpinnerFactory.java:147)
2022-09-15 09:54:09.816 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.widget.ANCSpinnerFactory.populateDescendants(ANCSpinnerFactory.java:139)
2022-09-15 09:54:09.816 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.widget.ANCSpinnerFactory.getViewsFromJson(ANCSpinnerFactory.java:109)
2022-09-15 09:54:09.816 29868-29868/org.smartregister.anc W/System.err:     at com.vijay.jsonwizard.interactors.JsonFormInteractor$1.run(JsonFormInteractor.java:232)
2022-09-15 09:54:09.816 29868-29868/org.smartregister.anc W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2022-09-15 09:54:09.816 29868-29868/org.smartregister.anc W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-09-15 09:54:09.816 29868-29868/org.smartregister.anc W/System.err:     at android.os.Looper.loop(Looper.java:193)
2022-09-15 09:54:09.816 29868-29868/org.smartregister.anc W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6819)
2022-09-15 09:54:09.816 29868-29868/org.smartregister.anc W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-09-15 09:54:09.816 29868-29868/org.smartregister.anc W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
2022-09-15 09:54:09.816 29868-29868/org.smartregister.anc W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)
2022-09-15 09:54:09.842 29868-29868/org.smartregister.anc W/System.err: org.json.JSONException: Value 8c0f8fd0-3268-4f22-8821-32ac070be5e7 of type java.lang.String cannot be converted to JSONObject
2022-09-15 09:54:09.843 29868-29868/org.smartregister.anc W/System.err:     at org.json.JSON.typeMismatch(JSON.java:112)
2022-09-15 09:54:09.843 29868-29868/org.smartregister.anc W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:163)
2022-09-15 09:54:09.843 29868-29868/org.smartregister.anc W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:176)
2022-09-15 09:54:09.843 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.util.Utils.getLocationsByParentId(Utils.java:1090)
2022-09-15 09:54:09.843 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.widget.ANCSpinnerFactory.populateLocationSpinner(ANCSpinnerFactory.java:147)
2022-09-15 09:54:09.843 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.widget.ANCSpinnerFactory.populateDescendants(ANCSpinnerFactory.java:139)
2022-09-15 09:54:09.843 29868-29868/org.smartregister.anc W/System.err:     at org.smartregister.anc.library.widget.ANCSpinnerFactory.getViewsFromJson(ANCSpinnerFactory.java:109)
2022-09-15 09:54:09.843 29868-29868/org.smartregister.anc W/System.err:     at com.vijay.jsonwizard.interactors.JsonFormInteractor$1.run(JsonFormInteractor.java:232)
2022-09-15 09:54:09.843 29868-29868/org.smartregister.anc W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2022-09-15 09:54:09.843 29868-29868/org.smartregister.anc W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-09-15 09:54:09.843 29868-29868/org.smartregister.anc W/System.err:     at android.os.Looper.loop(Looper.java:193)
2022-09-15 09:54:09.843 29868-29868/org.smartregister.anc W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6819)
2022-09-15 09:54:09.843 29868-29868/org.smartregister.anc W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-09-15 09:54:09.843 29868-29868/org.smartregister.anc W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
2022-09-15 09:54:09.843 29868-29868/org.smartregister.anc W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)
2022-09-15 09:54:10.005 29868-29948/org.smartregister.anc D/Surface: Surface::disconnect(this=0x754e330000,api=1)
2022-09-15 09:54:10.007 29868-29868/org.smartregister.anc D/View: [Warning] assignParent to null: this = DecorView@a7d96b3[Loading]
2022-09-15 09:54:10.101 29868-29868/org.smartregister.anc I/Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
2022-09-15 09:54:10.233 29868-29879/org.smartregister.anc I/artregister.an: Background concurrent copying GC freed 427233(19MB) AllocSpace objects, 130(3MB) LOS objects, 40% free, 35MB/59MB, paused 280us total 405.001ms
2022-09-15 09:54:10.509 29868-29948/org.smartregister.anc D/Surface: Surface::disconnect(this=0x75535a9000,api=1)
2022-09-15 09:54:11.248 29868-29868/org.smartregister.anc W/RenderThread: type=1400 audit(0.0:269972): avc: denied { search } for name="battery" dev="sysfs" ino=6950 scontext=u:r:untrusted_app:s0:c92,c257,c512,c768 tcontext=u:object_r:sysfs_batteryinfo:s0 tclass=dir permissive=0
2022-09-15 09:54:21.280 29868-29868/org.smartregister.anc W/RenderThread: type=1400 audit(0.0:269973): avc: denied { search } for name="battery" dev="sysfs" ino=6950 scontext=u:r:untrusted_app:s0:c92,c257,c512,c768 tcontext=u:object_r:sysfs_batteryinfo:s0 tclass=dir permissive=0
2022-09-15 09:54:31.308 29868-29868/org.smartregister.anc W/RenderThread: type=1400 audit(0.0:269975): avc: denied { search } for name="battery" dev="sysfs" ino=6950 scontext=u:r:untrusted_app:s0:c92,c257,c512,c768 tcontext=u:object_r:sysfs_batteryinfo:s0 tclass=dir permissive=0
2022-09-15 09:54:39.291 29868-29868/org.smartregister.anc W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
2022-09-15 09:54:39.293 29868-29868/org.smartregister.anc W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
2022-09-15 09:54:39.295 29868-29868/org.smartregister.anc W/IInputConnectionWrapper: getSelectedText on inactive InputConnection
2022-09-15 09:54:39.553 29868-29909/org.smartregister.anc D/TransportRuntime.SQLiteEventStore: Storing event with priority=DEFAULT, name=FIREPERF for destination cct
2022-09-15 09:54:39.580 29868-29909/org.smartregister.anc D/TransportRuntime.JobInfoScheduler: Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lDY2traUg4aTJaQVJ3T3MxTEV6RktsZDE1YU9HOG96S28=) is already scheduled. Returning...
2022-09-15 09:54:44.410 29868-29948/org.smartregister.anc D/Surface: Surface::disconnect(this=0x754dfa4000,api=1)
2022-09-15 09:54:44.425 29868-29909/org.smartregister.anc D/TransportRuntime.CctTransportBackend: Making request to: https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/batchlog
2022-09-15 09:54:44.513 29868-29909/org.smartregister.anc I/artregister.an: The ClassLoaderContext is a special shared library.
2022-09-15 09:54:44.529 29868-29909/org.smartregister.anc I/System.out: [OkHttp] sendRequest>>
2022-09-15 09:54:44.532 29868-29909/org.smartregister.anc I/System.out: [OkHttp] sendRequest<<
2022-09-15 09:54:46.816 29868-29909/org.smartregister.anc I/TransportRuntime.CctTransportBackend: Status Code: 200
2022-09-15 09:54:46.817 29868-29909/org.smartregister.anc I/TransportRuntime.CctTransportBackend: Content-Type: application/json; charset=UTF-8
2022-09-15 09:54:46.817 29868-29909/org.smartregister.anc I/TransportRuntime.CctTransportBackend: Content-Encoding: gzip

**Comment by Naima-Bashir** [comment]
Hi @dodosi Kindly ensure the root location identifier and default plan id's specified in the envs exists in the server.

**Comment by dodosi** [comment]
@Naima-Bashir The plan IDs seems to be available. Refer to the screenshots below
![image](https://user-images.githubusercontent.com/8068177/190591085-20249fd3-5aa5-4721-9531-5439cac51480.png)
![image](https://user-images.githubusercontent.com/8068177/190591127-4a4f388f-e005-4137-a18c-a0d0fbf50134.png)
![image](https://user-images.githubusercontent.com/8068177/190591171-c0898959-519d-4516-941c-5c566f929b33.png)
